surfaces = [
    "albite_dust",
    "andesite",
    "basalt_glass",
    "basalt_large",
    "basalt_small",
    "basalt_tuff",
    "diorite",
    "gabbro",
    "granite",
    "greybody",
    "harzburgite",
    "hematite",
    "lherzolite",
    "lunar_anorthosite",
    "lunar_marebasalt",
    "magnesium_sulphate",
    "mars_basalticshergottite",
    "mars_breccia",
    "norite",
    "phonolite",
    "pyrite",
    "rhyolite",
    "syenite",
    "tephrite",
    "tholeiitic_basalt",
    "trachy_andesite",
    "trachy_basalt",
    "trachyte",
    "ultramafic" ]
