[atmospheres]
001bar_N2_H2O_O3_case3 = "0.01 bar N$_2$ + 30 % H$_2$O + 1000 ppm O$_3$"
01bar_N2_H2O_O3_case3 = "0.1 bar N$_2$ + 30 % H$_2$O + 1000 ppm O$_3$"
1bar_N2_H2O_O3_case3 = "1 bar N$_2$ + 30 % H$_2$O + 1000 ppm O$_3$"
10bar_N2_H2O_O3_case3 = "10 bar N$_2$ + 30 % H$_2$O + 1000 ppm O$_3$"
100bar_N2_H2O_O3_case3 = "100 bar N$_2$ + 30 % H$_2$O + 1000 ppm O$_3$"
001bar_N2_H2O_O3_case4 = "0.01 bar N$_2$ + 30 % H$_2$O + 100 ppm O$_3$"
01bar_N2_H2O_O3_case4 = "0.1 bar N$_2$ + 30 % H$_2$O + 100 ppm O$_3$"
1bar_N2_H2O_O3_case4 = "1 bar N$_2$ + 30 % H$_2$O + 100 ppm O$_3$"
10bar_N2_H2O_O3_case4 = "10 bar N$_2$ + 30 % H$_2$O + 100 ppm O$_3$"
100bar_N2_H2O_O3_case4 = "100 bar N$_2$ + 30 % H$_2$O + 100 ppm O$_3$"
100bar_H2O_O3_case2 = "100 bar H$_2$O + 1000 ppm O$_3$"
10bar_H2O_O3_case2 = "10 bar H$_2$O + 1000 ppm O$_3$"
1bar_H2O_O3_case2 = "1  bar H$_2$O + 1000 ppm O$_3$"
01bar_H2O_O3_case2 = "0.1 bar H$_2$O + 1000 ppm O$_3$"

[highlights]
atmospheres = ["01bar_N2_H2O_O3_case4"]