[surfaces]
"harzburgite" = "Harzburgite"
"ultramafic" = "Peridotite"
"granite" = "Granite"
"albite_dust" = "Albite (dust)"
"magnesium_sulphate" = "Magnesium sulfate"
"trachyte" = "Trachyte"


[highlights]
# List of surface keys to highlight in your plot
surfaces = ["harzburgite"]
